version: '3'
services:

  web:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/

  app:
    build: ./php
    working_dir: /var/www
    depends_on:
      - db
    volumes:
      - ./src:/var/www/
      - ./php/php.ini:/usr/local/etc/php/php.ini

  db:
    image: mysql:5.7
    ports:
      - "3316:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=develop
    volumes:
      - db:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/my.cnf

volumes:
  db:
